FROM resin/%%RESIN_MACHINE_NAME%%-python
ENV INITSYSTEM on
# Resin wifi connect
WORKDIR /usr/src/app
# Python Flask Server
COPY ./server/requirements.txt /server/requirements.txt
WORKDIR /server
ENV READTHEDOCS True
RUN pip install -r ./requirements.txt
COPY ./server/server.py /server/server.py
COPY ./server/motion_detector.py /server/motion_detector.py
COPY ./server/camera.py /server/camera.py
CMD ["python", "server.py"]

